In [36]:
import numpy as np
from sklearn.datasets import load_diabetes

In [37]:
X, y = load_diabetes(return_X_y = True)

In [38]:
X.shape

(442, 10)

In [39]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [40]:
y.shape

(442,)

# Using sklearn's Linear Regression

In [41]:
from sklearn.model_selection import train_test_split # Import train_test_split for splitting data into training and testing sets

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2) # Split the dataset into training and testing sets

In [43]:
print(X_train.shape) # Display the shape of the training features
print(X_test.shape) # Display the shape of the testing features

(353, 10)
(89, 10)


In [44]:
from sklearn.linear_model import LinearRegression # Import LinearRegression model from sklearn

In [45]:
lr = LinearRegression() # Create an instance of the Linear Regression model

In [46]:
lr.fit(X_train, y_train) # Train the Linear Regression model using the training data

LinearRegression()

In [47]:
y_pred = lr.predict(X_test) # Make predictions on the test data

In [48]:
from sklearn.metrics import r2_score # Import r2_score for evaluating model performance

In [49]:
print("R2 Score: ", r2_score(y_test, y_pred)) # Calculate and print the R2 score for the model

R2 Score:  0.4399338661568968


In [50]:
lr.coef_ # Display the coefficients (slopes) of the linear regression model

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [51]:
lr.intercept_ # Display the intercept of the linear regression model

np.float64(151.88331005254167)

# Making our own Linear Regression Class

In [52]:
class MeraLR:
  # Custom Linear Regression class from scratch
  def __init__(self):
    self.coef_ = None # Initialize coefficients to None
    self.intercept_ = None # Initialize intercept to None

  def fit(self, X_train, y_train):
    # Add a column of ones to X_train for the intercept term
    X_train = np.insert(X_train, 0, 1, axis = 1)

    # Calculate the coefficients (betas) using the normal equation: (X_T * X)^-1 * X_T * y
    betas = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = betas[0] # The first element is the intercept
    self.coef_ = betas[1:] # The remaining elements are the coefficients for features

  def predict(self, X_test):
    # Make predictions using the formula: y_pred = X_test * coef_ + intercept_
    y_pred = np.dot(X_test, self.coef_) + self.intercept_
    return y_pred

In [53]:
reg = MeraLR() # Create an instance of our custom Linear Regression model

In [54]:
reg.fit(X_train, y_train) # Train our custom Linear Regression model

In [55]:
X_train.shape # Display the shape of the training features before adding the intercept column

(353, 10)

In [56]:
np.insert(X_train, 0, 1, axis = 1).shape # Display the shape of X_train after adding the intercept column

(353, 11)

In [57]:
y_pred = reg.predict(X_test) # Make predictions on the test data using our custom model

In [58]:
print("R2 Score: ", r2_score(y_test, y_pred)) # Calculate and print the R2 score for our custom model

R2 Score:  0.43993386615689634


In [59]:
reg.coef_ # Display the coefficients of our custom linear regression model

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [60]:
reg.intercept_ # Display the intercept of our custom linear regression model

np.float64(151.88331005254165)

In [61]:
import numpy as np # Import numpy for numerical operations
from sklearn.datasets import load_diabetes # Import load_diabetes to load the dataset